version: "3"
services:
   nginx:
     container_name: nginx
     image: nginx
     volumes:
       - ./default.conf:/etc/nginx/conf.d/default.conf
     ports:
       - 8080:80
     networks:
       - proxy

   server:
     container_name: server
     image: 9962976521/dhamu-app:1.0
     networks:
       - proxy 

networks:
  proxy:

