version: "3"
services:
   nginxwebapp:
     container_name: nginx-app
     image: nginx

     volumes:
       - $PWD/final/nginx.conf:/etc/nginx/conf.d/nginx.conf
     ports:
       - 8080:80
     networks: 
       - dhamo

   customapp:
     container_name: webapp
     image: 9962976521/dhamu-app:1.0
     ports:
       - 8088:80
     networks: 
       - dhamo
networks:
  dhamo:
  external: 
